### ISSUE TITLE
Custom Repo, not able to edit

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#78] opened 2016-10-31 10:41 UTC
Been playing with a custom repo but get a ysod when going to the edit view, seems that it isn't picking up the correct alias but using the primary key field instead

```
An error occured

No UIOMatic type with alias Nibble Newsletter found 
```

Nibble Newsletter is my identifier 

what I get in the query string 

`http://localhost:53960/umbraco#/uiomatic/uiomatic/edit/Nibble%20Newsletter%3Fta=Lists`

So it should look for Lists instead

**Comment by mattbrailsford** [comment] 2016-10-31 11:03
What does your repo implementation look like?

**Comment by TimGeyssens** [comment] 2016-10-31 11:21
Currently I got this

`    public class ListRepo : AbstractUIOMaticRepository<Models.List, string>
    {
        public override List Create(List entity)
        {
            throw new NotImplementedException();
        }

        public override void Delete(string[] ids)
        {
            throw new NotImplementedException();
        }

        public override List Get(string id)
        {
            return Helper.GetLists().Result.FirstOrDefault(x => x.Id == id);
        }

        public override IEnumerable<List> GetAll(string sortColumn = "", string sortOrder = "")
        {
           return Helper.GetLists().Result;
        }

        public override UIOMaticPagedResult<List> GetPaged(int pageNumber, int itemsPerPage, string searchTerm = "", IDictionary<string, string> filters = null, string sortColumn = "", string sortOrder = "")
        {
            throw new NotImplementedException();
        }

        public override long GetTotalRecordCount()
        {
            throw new NotImplementedException();
        }

        public override List Update(List entity)
        {
            throw new NotImplementedException();
        }
    }`

And My List model looks like

`    [UIOMatic("Lists", "Lists", "List",
        RepositoryType = typeof(ListRepo))]
    public class List
    {
        [PrimaryKeyColumn]
        public string Id { get; set; }

        [UIOMaticField]
        public string Name { get; set; }

        [UIOMaticField]
        public DateTime DateCreated { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }`

**Comment by TimGeyssens** [comment] 2016-10-31 11:21
(trying a sample API integration with Campaign Monitor)

**Comment by mattbrailsford** [comment] 2016-10-31 11:29
AbstractUIOMaticRepository has generic attributes, the first being your entity type, and then second being your primary key type, have you got those set correct?

    public class ListRepo : AbstractUIOMaticRepository<List, string>

**Comment by TimGeyssens** [comment] 2016-10-31 11:31
Yup think so 

public class ListRepo : AbstractUIOMaticRepository<Models.List, string>

**Comment by mattbrailsford** [comment] 2016-10-31 11:40
You need to format you response as code, Github keeps stripping the angle brackets :) 

But I think I've spotted where the issue is. Line 21 in edit.controller.js is expecting the ID to be a number, so we need to update this code. We could probably just check to see if there is a "ta" querystring param and if so, we know it's an edit, otherwise it's a create, so should be an east fix.

Have you merged v2 code into master yet? or is it staying in the v2 branch? Also, have you tagged the release? as we could do with making sure that happens before any more changes happen.

**Comment by TimGeyssens** [comment] 2016-10-31 11:45
Ah yes need to format as code :) yeah thought it would be something like that. 

Thought I tagged but don't see it

**Comment by mattbrailsford** [comment] 2016-10-31 11:48
Should be able to change hadId to

    var hasId = qs["ta"]; 

Will commit once tagged etc though

**Closed** 2016-10-31 11:51 UTC
Labels: bug

**Comment by TimGeyssens** [comment] 2016-10-31 12:21
It works and man this is powerful stuff, great great job on the Repo!

**Comment by mattbrailsford** [comment] 2016-10-31 12:22
Sweeeet :)
