### ISSUE TITLE
No Data Entry Fields in Backoffice - Umbraco V8

### ISSUE THREAD

**Issue by angryloner** [TimGeyssens/UIOMatic#154] opened 2020-06-18 04:51 UTC
I've installed v 3.0.8 via nuget - `Install-Package Nibble.Umbraco.UIOMatic -Version 3.0.8` - and followed the instructions in the github readme to create my database table and Model class.

When I open the Umbraco Backoffice there are no fields when I try to create a person:
![image](https://user-images.githubusercontent.com/947697/84977198-1e87f680-b16d-11ea-8220-b12c2a00e920.png)

If I manually add a person via the database, there are no fields when I try to update them:
![image](https://user-images.githubusercontent.com/947697/84977242-3790a780-b16d-11ea-8d2f-750735c80ec8.png)

As an aside, the menu item seems a bit weird too:
![image](https://user-images.githubusercontent.com/947697/84977275-4b3c0e00-b16d-11ea-967b-57821165e142.png)

Here's how my solution looks:
![image](https://user-images.githubusercontent.com/947697/84977333-6c046380-b16d-11ea-8eba-ac6f7ee396f4.png)

And my model:

```
using NPoco;
using System.ComponentModel.DataAnnotations;
using UIOMatic.Attributes;
using Umbraco.Core.Persistence.DatabaseAnnotations;

namespace toolkit_umbraco_poc.Models
{
    [UIOMatic("people", "People", "Person", FolderIcon = "icon-users", ItemIcon = "icon-user")]
    [TableName("People")]
    public class Person
    {
        [PrimaryKeyColumn(AutoIncrement = true)]
        public int Id { get; set; }

        [Required]
        [UIOMaticField(Name = "First name", Description = "Enter the persons first name")]
        public string FirstName { get; set; }

        [Required]
        [UIOMaticField(Name = "Last name", Description = "Enter the persons last name")]
        public string LastName { get; set; }

        [UIOMaticField(Name = "Picture", Description = "Select a picture", View = UIOMatic.Constants.FieldEditors.File)]
        public string Picture { get; set; }

        public override string ToString()
        {
            return FirstName + " " + LastName;
        }

    }
}
```

**Comment by TimGeyssens** [comment] 2020-06-18 08:37
Odd, any js error happening?

**Comment by TimGeyssens** [comment] 2020-06-18 09:16
Ok I see seems to be caused by merging in the latest pr , will fix

**Comment by TimGeyssens** [comment] 2020-06-18 10:13
Fixed in v3.0.9 that is currently being build... so just nuget upgrade once that is on nuget and it should work.

**Closed as completed by TimGeyssens** 2020-06-18 10:13 UTC

**Comment by angryloner** [comment] 2020-06-18 11:18
That's fixed it for me. Thanks for the speedy response and this great tool!

**Comment by TimGeyssens** [comment] 2020-06-18 11:45
Awesome, thanks for confirming!
