### ISSUE TITLE
Should the default prop order by a-z or by order they appear on model

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#50] opened 2016-10-24 14:00 UTC
Since it seems in v2 beta default they are ordered a-z unless you specify an order.. but to avoid having to specify the order it might be nice to have them ordered as they appear on the model

**Comment by mattbrailsford** [comment] 2016-10-24 14:07
The problem is we use reflection to get a list of properties and the GetProperties method is not guaranteed to give you the properties in declaration order. I'm pretty sure I implemented the order param because I saw my properties moving around when .NET was returning property info in a different order (it's also tricky once you start having POCO's with inheritance).

**Comment by TimGeyssens** [comment] 2016-10-24 14:08
Ok fair enough :)

**Comment by mattbrailsford** [comment] 2016-10-24 14:09
We had a similar thing in Ditto with using attributes, we have to declare an Order param. It's ugly I know, but it's the only guaranteed way you can ensure an order.

**Comment by TimGeyssens** [comment] 2016-10-24 14:14
True haven't thought of inheritance

**Comment by mattbrailsford** [comment] 2016-10-24 14:36
Just had a quick look round, and might have found a bit of a solution (i did come across this with ditto, but wouldn't work for us then, but might work for us here). 

[CallerLineNumber] can be used to get the current line number of the piece of code running so we may be able to use that to pre-populate the order property. I'll have a play tonight and see if it could work. It still wouldn't work for inheritance, but would be fine for simple models.

**Comment by mattbrailsford** [comment] 2016-10-24 16:51
Ok, so this works using [CallerLineNumber], I just want to check what you think. The way this works is that it detects the line number of the attribute in the code and sets the order property of that field to that line number so you end up with values like 22, 34, 47, etc (ie, not sequential). This all works fine if you don't define any values for Order at all, but if you do define an Order (or you use inheritance) we will probably want to say to set Order explicitly for all fields, otherwise you'll end up with some fairly odd Order values :)

Does this sound reasonable?

**Comment by TimGeyssens** [comment] 2016-10-24 17:57
Yeah I think that sounds pretty good :) For small models you won't bother with the order but once you have a bigger one (with tabs and all) you'll start looking into ordering... Ace!

**Comment by mattbrailsford** [comment] 2016-10-24 18:29
Cool, committed code :)

**Closed by mattbrailsford** 2016-10-24 18:29 UTC
